POST http://localhost:3001/products HTTP/1.1
content-type: application/json

{
  "name": "Camo Yellow",
  "price": 51.95,
  "description": "The Camo Series of Backpacks for built for the tuff breeds. they’re designed with Ruggedness but also being compact. this backpack is suitable for all sizes of dogs from small to large.",
  "countInStock": 50,
  "mainImageUrl": "camo-yellow/camoyellow1",
  "allImages": [
    "camo-yellow/71-min.png",
    "camo-yellow/72-min.png",
    "camo-yellow/73-min.png",
    "camo-yellow/74-min.png",
    "camo-yellow/75-min.png",
    "camo-yellow/76-min.png"
  ],
  "rating": 5
}